[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10